version: "3.1"
services:
  bot:
    build: .
    links:
      - db
  db:
    image: postgres:12.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
