version: "3.1"
services:
  bot:
    build:
      context: ../../.
      dockerfile: ./docker/Dockerfile
    links:
      - db
  db:
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
